baseURL = "https://openhistorymap.github.io/"
languageCode = "en-us"
title = "Open History Map"
theme = "ananke"
toc = true
sectionPagesMenu = "main"

googleAnalytics = "UA-104661756-3"

[menu]
  [[menu.main]]
    identifier = "map"
    name = "Map"
    title = "Map"
    url = "https://map.openhistorymap.org"
    weight = -110
  [[menu.main]]
    identifier = "index"
    name = "Index"
    title = "Index"
    url = "https://index.openhistorymap.org"
    weight = -109
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "The Blog"
    url = "https://blog.openhistorymap.org/"
    weight = -105
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about"
    weight = -102
  [[menu.main]]
    identifier = "help"
    name = "Help us!"
    title = "Help us"
    url = "/help"
    weight = 1104
  

    
    

[params]
  site_logo = "/LogoKAINUA-1536x769.png"
  facebook = "https://www.facebook.com/openhistorymap"
  twitter = "https://twitter.com/ohm_open"
  youtube = "https://www.youtube.com/channel/UCsyTVfrwSdCIj9MYjkn6pFg"
  github = "https://github.com/openhistorymap"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-gray"
  cover_dimming_class = "bg-black-60"
  recent_posts_number = 5